### ISSUE TITLE
fe2o3-amqp-ws: TLS connect functions are feature gated, so a library cannot depend on the crate without selecting a TLS stack

### ISSUE THREAD

**Issue by j7nw4r** [minghuaw/fe2o3-amqp#356]
## Summary

`fe2o3-amqp-ws` 0.16.0 puts every TLS connect function behind `#[cfg(any(feature = "native-tls", feature = "native-tls-vendored", feature = "rustls-tls-native-roots", feature = "rustls-tls-webpki-roots"))]`. A crate that depends on `fe2o3-amqp-ws` with no TLS feature compiles, but a call to `connect_tls_with_config` fails with E0599. The gates are at `fe2o3-amqp-ws/src/native.rs` lines 192 to 206 and 253 to 267 in 0.16.0. They are at lines 194 to 199 and 255 to 260 on `main`.

Reproduction with `fe2o3-amqp-ws` 0.16.0 and no features:

```toml
[dependencies]
fe2o3-amqp-ws = "0.16"
```

```rust
use fe2o3_amqp_ws::WebSocketStream;

pub async fn open() {
    let _ = WebSocketStream::connect_tls_with_config("wss://example.com", None, false, None).await;
}
```

```
error[E0599]: no associated function or constant named `connect_tls_with_config` found for struct `WebSocketStream<S>` in the current scope
```

## Motivation

A library crate that offers an AMQP-over-WebSockets transport must let the application select the TLS stack. `reqwest` shows the shape. A library depends on `reqwest` with no TLS feature, the library builds, and the application adds the stack. The same layout does not build on `fe2o3-amqp-ws`, because the connect function does not exist until a TLS feature is on. The library must therefore select a stack for all of its users, or publish a feature that cannot build on its own.

The Azure SDK for Rust meets this in `azure_core_amqp`, which adds an AMQP-over-WebSockets transport in Azure/azure-sdk-for-rust#4596.

The selected stack is also not deterministic. `connect_tls_with_config` accepts `Option<Connector>`. With `None`, `tokio-tungstenite` selects the stack from its own features, and it prefers native-tls when that feature is on (`tokio-tungstenite` 0.26.2, `src/tls.rs` lines 218 to 230). Cargo unifies features across the whole graph, so an unrelated dependency can change which stack a `wss://` connection uses.

## Proposal

Add a connect function that takes the connector and that carries no feature gate. `tokio_tungstenite::Connector` is available under the default features of `tokio-tungstenite`, and the `Connector::Plain` variant has no gate. The function can send `None` and `Connector::Plain` to `connect_async_with_config`, which needs no TLS feature, and send a TLS connector to the current path.

This lets a library build with no TLS feature, and it lets an application pin the stack. The change only adds API, so a minor version is sufficient.

The re-export of `tokio_tungstenite` on `main` (#353) helps here, because a caller can then name `Connector` without a separate dependency. It does not close this report, because the connect functions still do not exist when no TLS feature is on.

**Comment by minghuaw** [comment]
A kind note that #353 itself is unreleased and breaking
