### PR TITLE
fix(ws): remove the TLS feature gate from the connect_tls_* functions

### LINKED ISSUE #356: fe2o3-amqp-ws: TLS connect functions are feature gated, so a library cannot depend on the crate without selecting a TLS stack
## Summary

`fe2o3-amqp-ws` 0.16.0 puts every TLS connect function behind `#[cfg(any(feature = "native-tls", feature = "native-tls-vendored", feature = "rustls-tls-native-roots", feature = "rustls-tls-webpki-roots"))]`. A crate that depends on `fe2o3-amqp-ws` with no TLS feature compiles, but a call to `connect_tls_with_config` fails with E0599. The gates are at `fe2o3-amqp-ws/src/native.rs` lines 192 to 206 and 253 to 267 in 0.16.0. They are at lines 194 to 199 and 255 to 260 on `main`.

Reproduction with `fe2o3-amqp-ws` 0.16.0 and no features:

```toml
[dependencies]
fe2o3-amqp-ws = "0.16"
```

```rust
use fe2o3_amqp_ws::WebSocketStream;

pub async fn open() {
    let _ = WebSocketStream::connect_tls_with_config("wss://example.com", None, false, None).await;
}
```

```
error[E0599]: no associated function or constant named `connect_tls_with_config` found for struct `WebSocketStream<S>` in the current scope
```

## Motivation

A library crate that offers an AMQP-over-WebSockets transport must let the application select the TLS stack. `reqwest` shows the shape. A library depends on `reqwest` with no TLS feature, the library builds, and the application adds the stack. The same layout does not build on `fe2o3-amqp-ws`, because the connect function does not exist until a TLS feature is on. The library must therefore select a stack for all of its users, or publish a feature that cannot build on its own.

The Azure SDK for Rust meets this in `azure_core_amqp`, which adds an AMQP-over-WebSockets transport in Azure/azure-sdk-for-rust#4596.

The selected stack is also not deterministic. `connect_tls_with_config` accepts `Option<Connector>`. With `None`, `tokio-tungstenite` selects the stack from its own features, and it prefers native-tls when that feature is on (`tokio-tungstenite` 0.26.2, `src/tls.rs` lines 218 to 230). Cargo unifies features across the whole graph, so an unrelated dependency can change which stack a `wss://` connection uses.

## Proposal

Add a connect function that takes the connector and that carries no feature gate. `tokio_tungstenite::Connector` is available under the default features of `tokio-tungstenite`, and the `Connector::Plain` variant has no gate. The function can send `None` and `Connector::Plain` to `connect_async_with_config`, which needs no TLS feature, and send a TLS connector to the current path.

This lets a library build with no TLS feature, and it lets an application pin the stack. The change only adds API, so a minor version is sufficient.

The re-export of `tokio_tungstenite` on `main` (#353) helps here, because a caller can then name `Connector` without a separate dependency. It does not close this report, because the connect functions still do not exist when no TLS feature is on.

### PR DESCRIPTION
**Pull request by j7nw4r**
## Summary

`fe2o3-amqp-ws` put all three `connect_tls_*` functions behind a feature gate. The gate tested the four TLS features of the crate itself. A crate that depended on `fe2o3-amqp-ws` with no TLS feature compiled. A call to `connect_tls_with_config` then failed with E0599.

```toml
[dependencies]
fe2o3-amqp-ws = { version = "0.16", default-features = false }
```

```rust
use fe2o3_amqp_ws::WebSocketStream;

pub async fn open() {
    let _ = WebSocketStream::connect_tls_with_config("wss://example.com", None, false, None).await;
}
```

```
error[E0599]: no associated function or constant named `connect_tls_with_config` found for struct `fe2o3_amqp_ws::WebSocketStream<S>` in the current scope
 --> src/lib.rs:4:30
  |
4 |     let _ = WebSocketStream::connect_tls_with_config("wss://example.com", None, false, None).await;
  |                              ^^^^^^^^^^^^^^^^^^^^^^^ associated function or constant not found in `fe2o3_amqp_ws::WebSocketStream<_>`
```

This change removes that gate. The three functions now exist in every feature build, and the snippet above compiles unchanged.

Closes #356.

## Motivation

A library crate that offers an AMQP-over-WebSockets transport must let the application select the TLS stack. `reqwest` uses this model. The old layout did not allow it. The library had to select a stack for all of its users. The alternative was a feature that could not build on its own. `azure_core_amqp` in the Azure SDK for Rust meets this in Azure/azure-sdk-for-rust#4596.

The library now names no TLS crate, and it enables no TLS feature of `fe2o3-amqp-ws`. It accepts the connector that the application passes to it.

```toml
# The library.
[dependencies]
fe2o3-amqp-ws = { version = "0.16", default-features = false }
```

```rust
use fe2o3_amqp_ws::tokio_tungstenite::Connector;
use fe2o3_amqp_ws::WebSocketStream;

pub async fn connect(addr: &str, connector: Option<Connector>) {
    let _ = WebSocketStream::connect_tls_with_config(addr, None, false, connector).await;
}
```

The application selects the stack and builds the connector. The re-export of `tokio_tungstenite` from #353 lets both crates name `Connector` without a separate dependency.

```toml
# The application.
[dependencies]
my-amqp-lib = "1"
fe2o3-amqp-ws = { version = "0.16", default-features = false, features = ["native-tls"] }
native-tls = "0.2"
```

```rust
use fe2o3_amqp_ws::tokio_tungstenite::Connector;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let tls = native_tls::TlsConnector::new()?;
    my_amqp_lib::connect("wss://example.com", Some(Connector::NativeTls(tls))).await;
    Ok(())
}
```

The gating of `tokio-tungstenite` 0.30 constrains the fix. `tokio-tungstenite` exports `Connector` under its `connect` default feature, so this crate can always name it. `tokio-tungstenite` gates `connect_async_tls_with_config` and `client_async_tls_with_config` behind its own TLS features. A crate cannot `cfg` on the features of a dependency. An ungated wrapper therefore cannot forward to those two functions in every build.

## Changes

Each entry point now goes through a private helper pair in `fe2o3-amqp-ws/src/native.rs`. One helper carries `cfg(any(<tls features>))`. It delegates to `tokio-tungstenite` unchanged. The other helper carries `cfg(not(any(<tls features>)))`. It takes the mode from the URI scheme, which is what `tokio-tungstenite` also does.

```rust
#[cfg(not(any(
    feature = "native-tls",
    feature = "native-tls-vendored",
    feature = "rustls-tls-native-roots",
    feature = "rustls-tls-webpki-roots"
)))]
async fn connect_async_with_connector(
    request: Request,
    config: Option<WebSocketConfig>,
    disable_nagle: bool,
    _connector: Option<tokio_tungstenite::Connector>,
) -> Result<
    (
        tokio_tungstenite::WebSocketStream<MaybeTlsStream<TcpStream>>,
        Response,
    ),
    tungstenite::Error,
> {
    use tungstenite::{client::uri_mode, error::UrlError, stream::Mode};

    match uri_mode(request.uri())? {
        Mode::Plain => connect_async_with_config(request, config, disable_nagle).await,
        Mode::Tls => Err(tungstenite::Error::Url(UrlError::TlsFeatureNotEnabled)),
    }
}
```

`Mode::Plain` forwards the request. Every `wrap_stream` arm of `tokio-tungstenite` returns `MaybeTlsStream::Plain` for `Mode::Plain`, so a `ws://` address behaves as before. `Mode::Tls` returns the same error value that `tokio-tungstenite` returns for the same condition, and this crate opens no socket first.

The helper never reads the connector. A `wss://` address therefore fails for every value of `connector`. This crate never downgrades a `wss://` address to a plaintext connection.

The public functions keep their exact signatures. The change adds no public name, no feature, and no `Error` variant. Removing a feature gate is additive, so the change is not breaking. The bound on `impl WebSocketStream<TokioWebSocketStream<MaybeTlsStream<S>>>` drops `Sync`. `tokio_tungstenite::client_async_tls_with_config` never required `Sync`, so this bound is a relaxation.

Three items go beyond the source fix:

1. `.github/workflows/ci.yml` and `CONTRIBUTING.md` gain the feature-matrix commands. No CI job built this crate with no TLS feature before, so the gate could come back unnoticed.
2. `fe2o3-amqp-ws/src/macros.rs` gains `doc(cfg(...))` on the target macros. The change removed the only two `doc(cfg(...))` attributes in the crate. That left `#![cfg_attr(docsrs, feature(doc_cfg))]` and the docs.rs `rustdoc-args` with no effect.
3. The crate-level docs named `WebSocketStream::from(ws_stream)` as the way to wrap a raw `tokio_tungstenite::WebSocketStream`. A caller cannot reach that path, because the only constructor of the inner `TokioWebSocketStream` is private. The paragraph now points at `connect_with_stream`.

One limit remains. `connect` and `connect_with_config` still select the TLS stack in a way that is not deterministic. Both take no connector and pass `None` down. `tokio-tungstenite` then selects the stack from its own features, and Cargo feature unification can change that selection. A scratch crate shows the split. It depends on `fe2o3-amqp-ws` with no TLS feature, and on `tokio-tungstenite` with `native-tls`, so unification gives `tokio-tungstenite` a TLS stack that this crate cannot reach.

```
connect_tls_with_config wss:// None       -> Some("URL error: TLS support not compiled in")
connect_tls_with_config wss:// Plain      -> Some("URL error: TLS support not compiled in")
connect_tls_with_config wss:// NativeTls  -> Some("URL error: TLS support not compiled in")
connect_tls_with_config ws://  plain      -> Some("IO error: Connection refused (os error 61)")
connect                 wss://            -> Err(HTTP error: 200 OK)
connect_with_config     wss://            -> Err(HTTP error: 200 OK)
```

The last two lines reached `example.com` over TLS and read an HTTP 200 instead of a 101, so the TLS handshake completed. The rustdoc of both functions now states this and points at `connect_tls_with_config`. A full fix needs a signature change, which is out of scope here.

## Test plan

`fe2o3-amqp-ws/tests/connector_api.rs` is new. A dev-dependency turns on `tokio-tungstenite/rustls-tls-webpki-roots` for the test build only. The tests therefore run in the unification case from the issue: `tokio-tungstenite` has a TLS stack and this crate has none. The dev-dependency adds no `ring` and no `aws-lc-rs` to the tree.

- `issue_356_snippet_resolves` holds the snippet from the issue verbatim. It fails to compile if the gate comes back.
- `rustls_variant_is_visible` fails to compile if the dev-dependency stops unifying. The runtime tests would then guard nothing.
- `wss_without_a_tls_feature_is_an_error` asserts `TlsFeatureNotEnabled` for `None` and for `Some(Connector::Plain)`.
- `ws_without_a_tls_feature_reaches_the_socket` asserts that a `ws://` address still reaches the socket.

These commands pass locally:

```
cargo check -p fe2o3-amqp-ws --no-default-features
cargo check -p fe2o3-amqp-ws --no-default-features --features native-tls
cargo check -p fe2o3-amqp-ws --no-default-features --features rustls-tls-native-roots
cargo check -p fe2o3-amqp-ws --no-default-features --features rustls-tls-webpki-roots
cargo check -p fe2o3-amqp-ws --all-features
cargo test -p fe2o3-amqp-ws --no-default-features
cargo test -p fe2o3-amqp-ws --all-features
cargo clippy -p fe2o3-amqp-ws --all-features --all-targets -- -D warnings
cargo clippy -p fe2o3-amqp-ws --no-default-features --all-targets -- -D warnings
cargo fmt --all -- --check
cargo doc -p fe2o3-amqp-ws --all-features --no-deps
cargo check --workspace --all-features
```

Every Rust snippet above comes from a scratch crate outside the workspace. Each one builds against this branch. The two library snippets fail against `main` with the E0599 shown at the top.

### CODE REVIEW

**Comment by j7nw4r** [comment]
@minghuaw Making this change. Do you want me to make sure you're (at)'d on changes going forward? I don't want to make too many changes without your blessing if you don't want it. This is still in your namespace.

File: fe2o3-amqp-ws/src/native.rs [hunk 1]
```diff
@@ -114,9 +120,15 @@ impl WebSocketStream<TokioWebSocketStream<MaybeTlsStream<TcpStream>>> {
     /// Calls [`tokio_tungstenite::connect_async_with_config`] internally with
     /// `"Sec-WebSocket-Protocol"` HTTP header of the `req` set to `"amqp"`
     /// 
-    /// `disable_nagle` specifies if the Nagle’s algorithm must be disabled, 
-    /// i.e. `set_nodelay(true)`. If you don’t know what the Nagle’s algorithm is, 
+    /// `disable_nagle` specifies if the Nagle’s algorithm must be disabled,
+    /// i.e. `set_nodelay(true)`. If you don’t know what the Nagle’s algorithm is,
```
[the remark this answers is not in the document]
Comment (j7nw4r) [reply fe2o3-amqp-ws/src/native.rs]: Fixed in 87ebb6d7. The apostrophes in `Nagle's` and `don't` are ASCII now, and the blank `///` line above them lost its trailing space. That was the only trailing whitespace left in the file.

I left the two curly double quotes further down at lines 470 and 483. They quote the AMQP WebSocket binding spec verbatim in comments this change does not otherwise touch, so cleaning them would add diff noise. Say the word if you want them converted too.
